name: amiro

packages:
  - app
  - packages/**

command:
  bootstrap:
    runPubGetInParallel: true

scripts:
  analyze:
    run: melos exec -- flutter analyze
    description: Run flutter analyze in every package.

  test:
    run: melos exec --dir-exists=test -- flutter test
    description: Run flutter test in every package that has a test directory.
